services:
  - type: web
    name: wolverine-photostudio-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: noreply@nerdyphotographer.in
      - key: NODE_ENV
        value: production
